// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core"
import * as __TAURI_EVENT from "@tauri-apps/api/event"

/** Commands */
export const commands = {
  killSidecar: () => __TAURI_INVOKE<void>("kill_sidecar"),
  installCli: () => typedError<string, string>(__TAURI_INVOKE("install_cli")),
  ensureServerReady: () => typedError<ServerReadyData, string>(__TAURI_INVOKE("ensure_server_ready")),
  getDefaultServerUrl: () => typedError<string | null, string>(__TAURI_INVOKE("get_default_server_url")),
  setDefaultServerUrl: (url: string | null) =>
    typedError<null, string>(__TAURI_INVOKE("set_default_server_url", { url })),
  parseMarkdownCommand: (markdown: string) =>
    typedError<string, string>(__TAURI_INVOKE("parse_markdown_command", { markdown })),
  notifyReady: () => typedError<null, null>(__TAURI_INVOKE("notify_ready")),
}

/** Events */
export const events = {
  deepLinkAction: makeEvent<DeepLinkAction>("deep-link-action"),
}

/* Types */
export type DeepLinkAction = { OpenProject: { directory: string; session: string | null } }

export type ServerReadyData = {
  url: string
  password: string | null
}

/* Tauri Specta runtime */
async function typedError<T, E>(
  result: Promise<T>,
): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
  try {
    return { status: "ok", data: await result }
  } catch (e) {
    if (e instanceof Error) throw e
    return { status: "error", error: e as any }
  }
}

function makeEvent<T>(name: string) {
  const base = {
    listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
    once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
    emit: (payload: T) =>
      __TAURI_EVENT.emit(name, payload) as unknown as T extends null
        ? () => Promise<void>
        : (payload: T) => Promise<void>,
  }

  const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
    listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
    once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
    emit: (payload: T) =>
      target.emit(name, payload) as unknown as T extends null ? () => Promise<void> : (payload: T) => Promise<void>,
  })

  return Object.assign(fn, base)
}
